using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Firepuma.Payments.Abstractions.DTOs.Requests;
using Firepuma.Payments.Abstractions.Infrastructure.Validation;
using Firepuma.Payments.FunctionAppManager.Commands;
using Firepuma.Payments.FunctionAppManager.Infrastructure.Helpers;
using Firepuma.Payments.Implementations.Config;
using Firepuma.Payments.Implementations.Factories;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos.Table;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

// ReSharper disable RedundantNameQualifier

namespace Firepuma.Payments.FunctionAppManager.HttpFunctions;

public class CreatePayFastClientApplication
{
    private readonly IMediator _mediator;

    public CreatePayFastClientApplication(
        IMediator mediator)
    {
        _mediator = mediator;
    }

    [FunctionName("CreatePayFastClientApplication")]
    public async Task<IActionResult> RunAsync(
        [HttpTrigger(AuthorizationLevel.Function, "post", Route = "CreatePayFastClientApplication/{applicationId}")]
        HttpRequest req,
        ILogger log,
        [Table("PayFastApplicationConfigs")] CloudTable applicationConfigTable,
        string applicationId,
        CancellationToken cancellationToken)
    {
        log.LogInformation("C# HTTP trigger function processed a request");

        var requestBody = await new StreamReader(req.Body).ReadToEndAsync();
        var requestDTO = JsonConvert.DeserializeObject<CreatePayFastClientApplicationRequest>(requestBody);

        if (requestDTO == null)
        {
            return HttpResponseFactory.CreateBadRequestResponse("Request body is required but empty");
        }

        if (!ValidationHelpers.ValidateDataAnnotations(requestDTO, out var validationResultsForRequest))
        {
            return HttpResponseFactory.CreateBadRequestResponse(new[] { "Request body is invalid" }.Concat(validationResultsForRequest.Select(s => s.ErrorMessage)).ToArray());
        }

        var functionHostKeyName = $"client-app-autogenerated-{applicationId}";

        var applicationSecret = PayFastClientAppConfig.GenerateRandomSecret();
        var newClientAppConfig = new PayFastClientAppConfig(
            "PayFast",
            applicationId,
            applicationSecret,
            requestDTO.IsSandbox,
            requestDTO.MerchantId,
            requestDTO.MerchantKey,
            requestDTO.PassPhrase);

        var commands = new IBaseRequest[]
        {
            new CreateFunctionHostSecretKey.Command(functionHostKeyName),
            new AddClientAppTableRecord.Command(applicationConfigTable, newClientAppConfig),
        };

        var responseObjects = new List<KeyValuePair<string, object>>();
        var logsForResponse = new List<string>();
        foreach (var command in commands)
        {
            var commandName = command.GetType().GetShortTypeName();

            var stopwatch = Stopwatch.StartNew();

            var response = await _mediator.Send(command, cancellationToken);
            responseObjects.Add(new KeyValuePair<string, object>($"{commandName} command", response));

            var durationInSeconds = stopwatch.Elapsed.TotalSeconds.ToString("F");
            logsForResponse.Add($"Command {commandName} duration {durationInSeconds}s");
        }

        responseObjects.Add(new KeyValuePair<string, object>("logs", logsForResponse));

        return new OkObjectResult(new Dictionary<string, object> { { "results", responseObjects } });
    }
}