using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Firepuma.PaymentsService.Abstractions.DTOs.Requests;
using Firepuma.PaymentsService.Abstractions.Infrastructure.Queues;
using Firepuma.PaymentsService.Abstractions.Infrastructure.Validation;
using Firepuma.PaymentsService.FunctionAppManager.Commands;
using Firepuma.PaymentsService.FunctionAppManager.Infrastructure.Helpers;
using Firepuma.PaymentsService.Implementations.Config;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos.Table;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

// ReSharper disable RedundantNameQualifier

namespace Firepuma.PaymentsService.FunctionAppManager.HttpFunctions;

public class CreatePayFastClientApplication
{
    private readonly IMediator _mediator;

    public CreatePayFastClientApplication(
        IMediator mediator)
    {
        _mediator = mediator;
    }

    [FunctionName("CreatePayFastClientApplication")]
    public async Task<IActionResult> RunAsync(
        [HttpTrigger(AuthorizationLevel.Function, "post", Route = "CreatePayFastClientApplication/{applicationId}")]
        HttpRequest req,
        ILogger log,
        [Table("PaymentsConfigPerApplication")] CloudTable clientAppConfigTable,
        string applicationId,
        CancellationToken cancellationToken)
    {
        log.LogInformation("C# HTTP trigger function processed a request");

        var serviceBusConnectionString = EnvironmentVariableHelpers.GetRequiredEnvironmentVariable("ServiceBusConnectionString");

        var requestBody = await new StreamReader(req.Body).ReadToEndAsync();
        var requestDTO = JsonConvert.DeserializeObject<CreatePayFastClientApplicationRequest>(requestBody);

        if (requestDTO == null)
        {
            return CreateBadRequestResponse("Request body is required but empty");
        }

        if (!ValidationHelpers.ValidateDataAnnotations(requestDTO, out var validationResultsForRequest))
        {
            return CreateBadRequestResponse(new[] { "Request body is invalid" }.Concat(validationResultsForRequest.Select(s => s.ErrorMessage)).ToArray());
        }

        var queueName = QueueNameFormatter.GetPaymentUpdatedQueueName(applicationId);

        var functionHostKeyName = $"client-app-autogenerated-{applicationId}";

        var newClientAppConfig = new ClientAppConfig(
            "PayFast",
            applicationId,
            requestDTO.IsSandbox,
            requestDTO.MerchantId,
            requestDTO.MerchantKey,
            requestDTO.PassPhrase);

        var commands = new IBaseRequest[]
        {
            new CreateQueue(serviceBusConnectionString, queueName),
            new CreateFunctionHostSecretKey(functionHostKeyName),
            new AddClientAppTableRecord(clientAppConfigTable, newClientAppConfig),
        };

        var responseObjects = new List<KeyValuePair<string, object>>();
        var logsForResponse = new List<string>();
        foreach (var command in commands)
        {
            var commandName = command.GetType().Name;

            var stopwatch = Stopwatch.StartNew();

            var response = await _mediator.Send(command, cancellationToken);
            responseObjects.Add(new KeyValuePair<string, object>($"{commandName} command", response));

            var durationInSeconds = stopwatch.Elapsed.TotalSeconds.ToString("F");
            logsForResponse.Add($"Command {commandName} duration {durationInSeconds}s");
        }

        //TODO:
        //  * Expand to create:
        //    * [DONE] Queues
        //    * [DONE] New Function Key/code to authenticate
        //    * [DONE] New Shared access policies key for client app to listen on Service Bus
        //  * [DONE] Rework each step (create queue, create function host secret key, etc) into a Task/Command
        //  * Add function to GetAllClientApplications
        //  * Add function to ...
        //  * Is there a native Azure way to authenticate the function calls (instead of 'code') and that can automatically derive the "Application Id" from the auth token?
        //  * Alternative way to secure is to generate AppSecret (for each AppId) so they cannot simply act on behalf of another app

        responseObjects.Add(new KeyValuePair<string, object>("logs", logsForResponse));

        return new OkObjectResult(new Dictionary<string, object> { { "results", responseObjects } });
    }

    private static IActionResult CreateBadRequestResponse(params string[] errors)
    {
        return new BadRequestObjectResult(new Dictionary<string, object>
        {
            { "Errors", errors }
        });
    }
}