name: Deploy Nuget packages

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '6.0'
  PACKAGE_VERSION: "0.3.1"

jobs:
  build-and-deploy:
    name: Deploy version ${{ env.PACKAGE_VERSION }}
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          dotnet restore Firepuma.Payments.Core
          dotnet restore Firepuma.Payments.Client
          dotnet restore Firepuma.Payments.FunctionApp
          dotnet restore Firepuma.Payments.FunctionAppManager
          dotnet restore Firepuma.Payments.Infrastructure
          dotnet restore Firepuma.Payments.Tests

      - name: Test
        run: dotnet test --no-restore

      - name: Package
        run: |
          dotnet pack --configuration Release --output . -p:PackageVersion=${{ env.PACKAGE_VERSION }} Firepuma.Payments.Core/Firepuma.Payments.Core.csproj
          dotnet pack --configuration Release --output . -p:PackageVersion=${{ env.PACKAGE_VERSION }} Firepuma.Payments.Client/Firepuma.Payments.Client.csproj

      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
