name: Unit Tests only

on:
  push:
    branches-ignore:
      - main

env:
  DOTNET_VERSION: '6.0'
  VERSION_SUFFIX: "build-${{ github.run_number }}"

jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          dotnet restore Firepuma.Payments.Core
          dotnet restore Firepuma.Payments.Client
          dotnet restore Firepuma.Payments.FunctionApp
          dotnet restore Firepuma.Payments.FunctionAppManager
          dotnet restore Firepuma.Payments.Implementations
          dotnet restore Firepuma.Payments.Tests

      - name: Test
        run: dotnet test --no-restore
